name: Build AutoReport EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl Pillow customtkinter pyinstaller

    - name: Build with PyInstaller
      # 💡 AutoReport_Test.py 파일을 AutoReport_test.exe로 굽습니다!
      run: pyinstaller --noconsole --onefile --name AutoReport_test AutoReport_Test.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        # 💡 [수정 포인트 1] 다운로드 받을 때 압축파일 이름도 멋지게 변경!
        name: AutoReport-exe
        # 💡 [핵심 수정 포인트 2] 깃허브가 찾을 파일 이름을 새 이름으로 완벽하게 맞춰줍니다!
        path: dist/AutoReport_test.exe
